import numpy as np
from numpy import pi
import pandas as pd
import click




@click.group()


def cmd_group():
    """_summary_ 
    """    
    pass
@click.option(
"-n",
"--number",
default=10,)


@cmd_group.command()
# @click.argument("number")

def sin(number):
    """gives list of autogenerated sin results 

    Args:
        number (int): give the amount of pieces you want to cut your range of 0-2 pie into
    """    

    x = np.linspace(0, 2 * pi, number)
    df = pd.DataFrame({"x": x, "sin (x)": np.sin(x)})
    print(df)
    return

@cmd_group.command()
# @click.argument("number")

def tan(number):
    """gives list of autogenerated tan results 

    Args:
        number (int): give the amount of pieces you want to cut your range of 0-2 pie into
    """        
    x = np.linspace(0, 2 * pi, number)
    df = pd.DataFrame({"x": x, "tan (x)": np.tan(x)})
    print(df)
    return

if __name__ == "__main__":
    cmd_group()

